version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - apierrors
  - apiserver
  - Ayaka
  - cenkalti
  - Factorio
  - fatcontext
  - gorcon
  - grpcotel
  - grpcpkg
  - healthz
  - httppkg
  - labstack
  - Neko
  - nekomeowww
  - nolint
  - nonamedreturns
  - opentelemetry
  - Otel
  - otelgrpc
  - otelhttp
  - protovalidate
  - RCON
  - samber
  - Unmute
ignoreWords: []
import: []
