name: Release SDK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          package_json_file: ./apis/sdk/typescript/package.json
      - uses: actions/setup-node@v5
        with:
          cache: pnpm
          node-version: latest
          registry-url: https://registry.npmjs.org
      - working-directory: apis/sdk/typescript
        run: pnpm install --frozen-lockfile
      - working-directory: apis/sdk/typescript
        run: pnpm run build
      - working-directory: apis/sdk/typescript
        run: pnpm publish -r --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
