name: Release SDK

on:
  push:
    tags:
      - "v*"

env:
  STORE_PATH: ""

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          package_json_file: ./apis/sdk/typescript/package.json

      - name: Install Node.js 24.x
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          # registry-url required. Learn more at
          # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Packages build
        run: pnpm run build

      - name: Packages publish
        run: pnpm run packages:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
